name: Build and release electron app

on:
  push:
    # branches:
    #   - main
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    # runs-on: macos-latest
    # runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .env
        run: |
          echo CESIUM_ION_TOKEN='${{ secrets.CESIUM_ION_TOKEN }}' >> application/electron-app/.env
        shell: bash

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: npm ci, build, and test for library/spirare-babylonjs
        run: |
          cd library/spirare-babylonjs
          npm ci
          npm run build --if-present
          # npm run test --if-present
        shell: bash

      - name: npm ci, build, and test for library/spirare-server
        run: |
          cd library/spirare-server
          npm ci
          npm run build --if-present
          npm run test --if-present
        shell: bash

      - name: npm ci, build, and test for application/electron-app (Win)
        if: runner.os == 'Windows'
        run: |
          cd application/electron-app
          npm ci
          npm run package:win --if-present -- --arch x64
          # npm run test --if-present
        shell: bash

      - name: npm ci, build, and test for application/electron-app (Mac)
        if: runner.os == 'macOS'
        run: |
          cd application/electron-app
          npm ci
          npm run package:mac --if-present -- --arch x64
          # npm run package:mac --if-present -- --arch arm64
          # npm run test --if-present
        shell: bash

      - name: Zip application folder (Win)
        if: runner.os == 'Windows'
        run: |
          cd application/electron-app/release-builds
          Compress-Archive -Path SpirareEditorDesktop-win32-x64\* -DestinationPath SpirareEditorDesktop-${{ github.ref_name }}-win32-x64.zip

      - name: Zip application folder (Mac)
        if: runner.os == 'macOS'
        run: |
          cd application/electron-app/release-builds
          ls
          zip -r SpirareEditorDesktop-${{ github.ref_name }}-darwin-x64.zip SpirareEditorDesktop-darwin-x64/*

      - name: Upload artifact for deployment job (Win)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-win32-x64
          path: application/electron-app/release-builds/SpirareEditorDesktop-${{ github.ref_name }}-win32-x64.zip

      - name: Upload artifact for deployment job (Mac)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-darwin-x64
          path: application/electron-app/release-builds/SpirareEditorDesktop-${{ github.ref_name }}-darwin-x64.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4

      - name: Print artifacts
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            electron-app-win32-x64/SpirareEditorDesktop-${{ github.ref_name }}-win32-x64.zip
            electron-app-darwin-x64/SpirareEditorDesktop-${{ github.ref_name }}-darwin-x64.zip

      - name: 'Delete artifact'
        uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            *
